namespace YtDlpDownloader.Services;

public sealed class LocalizationService
{
    public const string Chinese = "zh-Hans";
    public const string English = "en";

    private readonly IReadOnlyDictionary<string, string> _texts;

    public LocalizationService(string language)
    {
        Language = Normalize(language);
        _texts = Language == English ? EnglishTexts : ChineseTexts;
    }

    public string Language { get; }

    public string this[string key] => _texts.TryGetValue(key, out var text)
        ? text
        : ChineseTexts.TryGetValue(key, out var fallback)
            ? fallback
            : key;

    public static string Normalize(string? language)
    {
        return string.Equals(language, Chinese, StringComparison.OrdinalIgnoreCase)
            ? Chinese
            : English;
    }

    private static readonly IReadOnlyDictionary<string, string> ChineseTexts = new Dictionary<string, string>
    {
        ["HeaderSteps"] = "1 输入链接  ->  2 选择清晰度  ->  3 开始下载",
        ["TooltipUrl"] = "视频 URL",
        ["GroupVideoInfo"] = "视频信息",
        ["GroupComponents"] = "组件状态",
        ["GroupSave"] = "保存设置",
        ["GroupLog"] = "日志",
        ["ButtonAnalyze"] = "解析",
        ["ButtonAnalyzing"] = "解析中...",
        ["ButtonRefresh"] = "刷新",
        ["ButtonRepair"] = "修复缺失",
        ["ButtonUpdateCore"] = "更新核心",
        ["ButtonBrowse"] = "选择",
        ["ButtonOpenFolder"] = "打开目录",
        ["ButtonOpenFile"] = "打开文件",
        ["ButtonCancelDownload"] = "取消下载",
        ["ButtonStartDownload"] = "开始下载",
        ["ButtonCopyLog"] = "复制日志",
        ["ButtonClear"] = "清空",
        ["LabelSaveDirectory"] = "保存目录",
        ["LabelFileName"] = "文件名",
        ["TabSimple"] = "简单下载",
        ["TabAdvanced"] = "高级格式",
        ["TabSettings"] = "下载设置",
        ["ColumnOption"] = "选项",
        ["ColumnKind"] = "类型",
        ["ColumnResolution"] = "清晰度",
        ["ColumnFormat"] = "格式",
        ["ColumnSummary"] = "说明",
        ["ColumnVideoCodec"] = "视频编码",
        ["ColumnAudioCodec"] = "音频编码",
        ["ColumnSize"] = "大小",
        ["ColumnExpression"] = "表达式",
        ["SettingsLanguage"] = "界面语言",
        ["SettingsMergeFormat"] = "合并格式",
        ["SettingsCookiesSource"] = "cookies 来源",
        ["SettingsCookiesFile"] = "cookies 文件",
        ["SettingsProxy"] = "代理",
        ["SettingsExtras"] = "附加内容",
        ["SettingsSubtitleFile"] = "字幕文件",
        ["SettingsAutoSubtitle"] = "自动字幕",
        ["SettingsThumbnail"] = "封面图片",
        ["SettingsSubtitleLanguages"] = "字幕语言",
        ["SettingsFileConflict"] = "文件冲突",
        ["SettingsRateLimit"] = "限速",
        ["SettingsRetryCount"] = "重试次数",
        ["SettingsConcurrentFragments"] = "并发分片数",
        ["SettingsExtraArgs"] = "高级参数",
        ["TooltipLanguage"] = "切换界面语言。第一版需要重启应用后完全生效。",
        ["TooltipMergeFormat"] = "mp4 兼容性最好；mkv 更包容；auto 交给 yt-dlp 决定。",
        ["TooltipCookiesSource"] = "B站 412、YouTube 登录验证时，推荐先选择 Chrome 或 Edge。浏览器读取失败时再选择 cookies.txt 文件。",
        ["TooltipCookiesFile"] = "仅 cookies 来源选择 cookies.txt 时使用。可用 Get cookies.txt LOCALLY 从浏览器导出。",
        ["TooltipProxy"] = "例如 http://127.0.0.1:7890；能直接访问视频网站就留空。",
        ["TooltipSubtitleFile"] = "下载作者上传的字幕，通常会生成额外字幕文件。",
        ["TooltipAutoSubtitle"] = "下载自动生成字幕，可能会生成额外字幕文件。",
        ["TooltipThumbnail"] = "额外下载视频封面图片。",
        ["TooltipSubtitleLanguages"] = "例如 zh-Hans,zh-CN,en；填 all 表示所有字幕。",
        ["TooltipFileConflict"] = "推荐自动改名，避免覆盖已有文件。",
        ["TooltipRateLimit"] = "例如 2M、500K；留空表示不限速。",
        ["TooltipRetryCount"] = "网络失败时自动重试次数。",
        ["TooltipConcurrentFragments"] = "默认 5。提高部分分片视频速度；网络不稳定时调低，范围 1-16。",
        ["TooltipExtraArgs"] = "手动追加 yt-dlp 参数。普通用户建议留空。",
        ["StatusEnterUrl"] = "输入视频链接，然后点击解析",
        ["StageWaitingLink"] = "等待链接",
        ["TitleNotParsed"] = "尚未解析视频",
        ["OptionsHintInitial"] = "输入视频链接后，点击解析即可看到推荐下载选项。",
        ["ActionInitial"] = "准备好后，将在这里显示当前选择和下载状态。",
        ["LanguageRestartNotice"] = "界面语言已保存，重启应用后完全生效。",
        ["LanguageRestartTitle"] = "需要重启",
        ["LanguageRestartMessage"] = "切换界面语言需要重启应用。\n\n是否现在重启并应用新语言？",
        ["LanguageRestartYes"] = "现在重启",
        ["LanguageRestartNo"] = "取消",
        ["FileConflictRename"] = "自动改名（推荐）",
        ["FileConflictSkip"] = "跳过已有文件",
        ["FileConflictOverwrite"] = "覆盖已有文件",
        ["ToolYtDlp"] = "下载核心 yt-dlp",
        ["ToolFfmpeg"] = "视频合并 ffmpeg",
        ["ToolJsRuntime"] = "兼容组件 Deno/Node",
        ["ToolNormal"] = "正常",
        ["ToolMissing"] = "缺失",
        ["ToolRecommended"] = "建议安装",
        ["ToolSystemPathYtDlp"] = "系统 PATH: yt-dlp.exe",
        ["ToolSystemPathFfmpeg"] = "系统 PATH: ffmpeg.exe",
        ["ComponentHint"] = "缺失时点“修复缺失”；解析失败或站点变化时点“更新核心”。",
        ["FormatBest"] = "最佳画质（推荐）",
        ["FormatSingleMp4"] = "单文件 MP4",
        ["FormatAudioOnly"] = "仅音频",
        ["FormatAudio"] = "音频",
        ["FormatNeedsMerge"] = "需合并",
        ["FormatSingleFile"] = "单文件",
        ["FormatAuto"] = "自动",
        ["FormatUnknown"] = "未知",
        ["FormatBestAvailable"] = "最高可用",
        ["FormatBestAudio"] = "最佳音频",
        ["FormatOrLower"] = "{0} 或以下",
        ["OptionsHintAdvanced"] = "高级格式适合了解 format_id 的用户；普通下载建议使用简单下载。需合并表示该格式只有视频轨，会自动和音频合并。",
        ["StageInvalidLink"] = "链接有误",
        ["StageAnalyzing"] = "解析中",
        ["StageAnalyzed"] = "已解析",
        ["StageParseFailed"] = "解析失败",
        ["StatusAnalyzing"] = "正在获取视频信息，请稍候...",
        ["StatusChooseQuality"] = "请选择清晰度，然后点击开始下载",
        ["OptionsHintAnalyzing"] = "正在读取标题、封面和可下载格式...",
        ["OptionsHintInvalidLink"] = "请粘贴完整的视频网址，然后再点击解析。",
        ["OptionsHintParseFailed"] = "没有获取到视频信息。可以换一个链接，或稍后重试。",
        ["DurationUnknown"] = "未知时长",
        ["ActionMergeAs"] = "，合并为 {0}",
        ["ActionWillDownload"] = "将下载：{0}{1}，保存到 {2}",
        ["StatusSelectDownloadOption"] = "请先选择下载选项",
        ["StageMissingComponent"] = "缺少组件",
        ["StatusMissingFfmpeg"] = "缺少 ffmpeg，无法完成视频合并",
        ["LogMissingFfmpeg"] = "ffmpeg 是必备组件。请把 ffmpeg.exe 放到 tools 目录后重试。",
        ["TaskPreparing"] = "准备下载",
        ["StageDownloading"] = "下载中",
        ["StatusDownloading"] = "正在下载，请保持窗口打开",
        ["TaskComplete"] = "完成",
        ["StageDownloadComplete"] = "下载完成",
        ["StatusDownloadComplete"] = "下载完成，可以打开文件或所在目录",
        ["LogCompleteNoFile"] = "下载完成，但未能自动定位最终文件。",
        ["LogSaved"] = "已保存: {0}",
        ["StageCanceled"] = "已取消",
        ["StatusCanceled"] = "下载已取消",
        ["LogCanceled"] = "下载已取消。",
        ["StageDownloadFailed"] = "下载失败",
        ["StatusDownloadFailed"] = "下载失败，详情见日志",
        ["StatusCanceling"] = "正在取消下载...",
        ["ActionStepPaste"] = "第 1 步：粘贴视频链接并点击解析。",
        ["ActionStepChoose"] = "第 2 步：解析后选择一个下载选项。",
        ["LanguageChinese"] = "简体中文",
        ["LanguageEnglish"] = "English"
    };

    private static readonly IReadOnlyDictionary<string, string> EnglishTexts = new Dictionary<string, string>
    {
        ["HeaderSteps"] = "1 Paste link  ->  2 Choose quality  ->  3 Start download",
        ["TooltipUrl"] = "Video URL",
        ["GroupVideoInfo"] = "Video Info",
        ["GroupComponents"] = "Components",
        ["GroupSave"] = "Save",
        ["GroupLog"] = "Log",
        ["ButtonAnalyze"] = "Analyze",
        ["ButtonAnalyzing"] = "Analyzing...",
        ["ButtonRefresh"] = "Refresh",
        ["ButtonRepair"] = "Repair Missing",
        ["ButtonUpdateCore"] = "Update Core",
        ["ButtonBrowse"] = "Browse",
        ["ButtonOpenFolder"] = "Open Folder",
        ["ButtonOpenFile"] = "Open File",
        ["ButtonCancelDownload"] = "Cancel",
        ["ButtonStartDownload"] = "Start Download",
        ["ButtonCopyLog"] = "Copy Log",
        ["ButtonClear"] = "Clear",
        ["LabelSaveDirectory"] = "Save To",
        ["LabelFileName"] = "File Name",
        ["TabSimple"] = "Simple",
        ["TabAdvanced"] = "Advanced",
        ["TabSettings"] = "Settings",
        ["ColumnOption"] = "Option",
        ["ColumnKind"] = "Type",
        ["ColumnResolution"] = "Quality",
        ["ColumnFormat"] = "Format",
        ["ColumnSummary"] = "Description",
        ["ColumnVideoCodec"] = "Video Codec",
        ["ColumnAudioCodec"] = "Audio Codec",
        ["ColumnSize"] = "Size",
        ["ColumnExpression"] = "Expression",
        ["SettingsLanguage"] = "Language",
        ["SettingsMergeFormat"] = "Merge Format",
        ["SettingsCookiesSource"] = "Cookies Source",
        ["SettingsCookiesFile"] = "Cookies File",
        ["SettingsProxy"] = "Proxy",
        ["SettingsExtras"] = "Extras",
        ["SettingsSubtitleFile"] = "Subtitles",
        ["SettingsAutoSubtitle"] = "Auto Subtitles",
        ["SettingsThumbnail"] = "Thumbnail",
        ["SettingsSubtitleLanguages"] = "Subtitle Languages",
        ["SettingsFileConflict"] = "File Conflict",
        ["SettingsRateLimit"] = "Rate Limit",
        ["SettingsRetryCount"] = "Retries",
        ["SettingsConcurrentFragments"] = "Concurrent Fragments",
        ["SettingsExtraArgs"] = "Extra Arguments",
        ["TooltipLanguage"] = "Change UI language. The first version requires restarting the app to fully apply it.",
        ["TooltipMergeFormat"] = "mp4 is most compatible; mkv is more flexible; auto lets yt-dlp decide.",
        ["TooltipCookiesSource"] = "For Bilibili 412 or YouTube sign-in checks, try Chrome or Edge first. Use cookies.txt if browser cookies cannot be read.",
        ["TooltipCookiesFile"] = "Only used when cookies source is cookies.txt. You can export it with Get cookies.txt LOCALLY.",
        ["TooltipProxy"] = "Example: http://127.0.0.1:7890. Leave empty if the site is reachable directly.",
        ["TooltipSubtitleFile"] = "Download subtitles uploaded by the author. This usually creates extra subtitle files.",
        ["TooltipAutoSubtitle"] = "Download auto-generated subtitles. This may create extra subtitle files.",
        ["TooltipThumbnail"] = "Download the video thumbnail as an extra image file.",
        ["TooltipSubtitleLanguages"] = "Example: zh-Hans,zh-CN,en. Use all to download every subtitle language.",
        ["TooltipFileConflict"] = "Auto rename is recommended to avoid overwriting existing files.",
        ["TooltipRateLimit"] = "Example: 2M or 500K. Leave empty for no speed limit.",
        ["TooltipRetryCount"] = "Number of automatic retries when the network fails.",
        ["TooltipConcurrentFragments"] = "Default is 5. Higher may speed up fragmented videos; lower it if the network is unstable. Range: 1-16.",
        ["TooltipExtraArgs"] = "Append custom yt-dlp arguments manually. Most users should leave this empty.",
        ["StatusEnterUrl"] = "Paste a video link, then click Analyze",
        ["StageWaitingLink"] = "Waiting",
        ["TitleNotParsed"] = "No video analyzed yet",
        ["OptionsHintInitial"] = "Paste a video link and click Analyze to see recommended download options.",
        ["ActionInitial"] = "Your selected option and download status will appear here.",
        ["LanguageRestartNotice"] = "Language saved. Restart the app to fully apply it.",
        ["LanguageRestartTitle"] = "Restart Required",
        ["LanguageRestartMessage"] = "Changing the interface language requires restarting the app.\n\nRestart now to apply the new language?",
        ["LanguageRestartYes"] = "Restart Now",
        ["LanguageRestartNo"] = "Cancel",
        ["FileConflictRename"] = "Auto rename (recommended)",
        ["FileConflictSkip"] = "Skip existing files",
        ["FileConflictOverwrite"] = "Overwrite existing files",
        ["ToolYtDlp"] = "Download core yt-dlp",
        ["ToolFfmpeg"] = "Media merge ffmpeg",
        ["ToolJsRuntime"] = "Compatibility runtime Deno/Node",
        ["ToolNormal"] = "OK",
        ["ToolMissing"] = "Missing",
        ["ToolRecommended"] = "Recommended",
        ["ToolSystemPathYtDlp"] = "System PATH: yt-dlp.exe",
        ["ToolSystemPathFfmpeg"] = "System PATH: ffmpeg.exe",
        ["ComponentHint"] = "If missing, click Repair Missing. If parsing fails after site changes, click Update Core.",
        ["FormatBest"] = "Best quality (recommended)",
        ["FormatSingleMp4"] = "Single-file MP4",
        ["FormatAudioOnly"] = "Audio only",
        ["FormatAudio"] = "Audio",
        ["FormatNeedsMerge"] = "Needs merge",
        ["FormatSingleFile"] = "Single file",
        ["FormatAuto"] = "Auto",
        ["FormatUnknown"] = "Unknown",
        ["FormatBestAvailable"] = "Best available",
        ["FormatBestAudio"] = "Best audio",
        ["FormatOrLower"] = "{0} or lower",
        ["OptionsHintAdvanced"] = "Advanced formats are for users who understand format_id. Most users should use Simple. Needs merge means the format only has a video track and will be merged with audio automatically.",
        ["StageInvalidLink"] = "Invalid link",
        ["StageAnalyzing"] = "Analyzing",
        ["StageAnalyzed"] = "Analyzed",
        ["StageParseFailed"] = "Parse failed",
        ["StatusAnalyzing"] = "Getting video info, please wait...",
        ["StatusChooseQuality"] = "Choose a quality, then click Start Download",
        ["OptionsHintAnalyzing"] = "Reading title, thumbnail, and available formats...",
        ["OptionsHintInvalidLink"] = "Paste a complete video URL, then click Analyze.",
        ["OptionsHintParseFailed"] = "No video info was found. Try another link or try again later.",
        ["DurationUnknown"] = "Unknown duration",
        ["ActionMergeAs"] = ", merge as {0}",
        ["ActionWillDownload"] = "Will download: {0}{1}, save to {2}",
        ["StatusSelectDownloadOption"] = "Choose a download option first",
        ["StageMissingComponent"] = "Missing component",
        ["StatusMissingFfmpeg"] = "ffmpeg is missing, so video merging cannot be completed",
        ["LogMissingFfmpeg"] = "ffmpeg is required. Put ffmpeg.exe in the tools folder and try again.",
        ["TaskPreparing"] = "Preparing",
        ["StageDownloading"] = "Downloading",
        ["StatusDownloading"] = "Downloading. Keep this window open.",
        ["TaskComplete"] = "Complete",
        ["StageDownloadComplete"] = "Download complete",
        ["StatusDownloadComplete"] = "Download complete. You can open the file or folder.",
        ["LogCompleteNoFile"] = "Download completed, but the final file could not be located automatically.",
        ["LogSaved"] = "Saved: {0}",
        ["StageCanceled"] = "Canceled",
        ["StatusCanceled"] = "Download canceled",
        ["LogCanceled"] = "Download canceled.",
        ["StageDownloadFailed"] = "Download failed",
        ["StatusDownloadFailed"] = "Download failed. See the log for details.",
        ["StatusCanceling"] = "Canceling download...",
        ["ActionStepPaste"] = "Step 1: paste a video link and click Analyze.",
        ["ActionStepChoose"] = "Step 2: choose a download option after analyzing.",
        ["LanguageChinese"] = "简体中文",
        ["LanguageEnglish"] = "English"
    };
}
